name: Update Projects

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-projects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main  # Explicitly checkout main branch
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install @octokit/rest axios
          echo "Dependencies installed successfully"
        
      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "GitHub token exists: ${{ secrets.GITHUB_TOKEN != '' }}"
          echo ".github/scripts contents:"
          ls -la .github/scripts/
          
      - name: Update Projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: "*"
        run: |
          echo "Starting update-projects.js..."
          node --trace-warnings .github/scripts/update-projects.js || {
            echo "Error running update-projects.js"
            echo "Node.js version: $(node -v)"
            echo "NPM version: $(npm -v)"
            exit 1
          }
          echo "update-projects.js completed"
        
      - name: Configure Git
        run: |
          echo "Configuring Git..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          echo "Git configured successfully"

      - name: Commit and push if changed
        run: |
          echo "Checking for changes..."
          if [ ! -f "src/app/hubbies/page.js" ]; then
            echo "Error: src/app/hubbies/page.js does not exist"
            ls -la src/app/hubbies/
            exit 1
          fi
          git add src/app/hubbies/page.js
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing..."
            git commit -m "Update projects from GitHub"
            echo "Pushing changes..."
            git push
            echo "Changes pushed successfully"
          fi
